"""empty message

Revision ID: 4f15e545b410
Revises: b9842df357f4
Create Date: 2016-06-04 22:45:17.963349

"""

# revision identifiers, used by Alembic.
revision = '4f15e545b410'
down_revision = 'b9842df357f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_files', sa.Column('url', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_files', 'url')
    ### end Alembic commands ###
